[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# API routes must come before SPA fallback
[[redirects]]
  from = "/api/threads/oauth/start"
  to = "/.netlify/functions/threads-oauth-start"
  status = 200

[[redirects]]
  from = "/api/threads/oauth/callback"
  to = "/.netlify/functions/threads-oauth-callback"
  status = 200

[[redirects]]
  from = "/api/ping"
  to = "/.netlify/functions/ping"
  status = 200

[[redirects]]
  from = "/api/threads/linked"
  to = "/.netlify/functions/threads-linked"
  status = 200

[[redirects]]
  from = "/api/debug/blobs-write"
  to = "/.netlify/functions/blobs-test-write"
  status = 200

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/api/threads/status"
  to = "/.netlify/functions/threads-status"
  status = 200

[[redirects]]
  from = "/api/threads/disconnect"
  to = "/.netlify/functions/threads-disconnect"
  status = 200

[[redirects]]
  from = "/api/threads/publish"
  to = "/.netlify/functions/threads-publish"
  status = 200

[[redirects]]
  from = "/api/threads/permalink"
  to = "/.netlify/functions/threads-permalink"
  status = 200

# 單頁應用：所有路由回退到 index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 若暫時不想被搜尋引擎收錄，可加自動回應標頭（非強保護）：
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[edge_functions]]
  path = "/*"
  function = "protect"

[[redirects]]
  from = "/api/threads/oauth/*"
  to = "/.netlify/functions/threads-oauth/:splat"
  status = 200


