[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# API routes must come before SPA fallback
[[redirects]]
  from = "/api/threads/oauth/*"
  to = "/.netlify/functions/threads-oauth/:splat"
  status = 200

[[redirects]]
  from = "/api/ping"
  to = "/.netlify/functions/ping"
  status = 200

# 單頁應用：所有路由回退到 index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 若暫時不想被搜尋引擎收錄，可加自動回應標頭（非強保護）：
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[edge_functions]]
  path = "/*"
  function = "protect"

[[redirects]]
  from = "/api/threads/oauth/*"
  to = "/.netlify/functions/threads-oauth/:splat"
  status = 200


