[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**/*"]

# 確保 Functions 在 SPA 回退之前處理
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# 單頁應用：所有路由回退到 index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 若暫時不想被搜尋引擎收錄，可加自動回應標頭（非強保護）：
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"


